### ISSUE TITLE
Volatility numbers are null for all ETFs

### ISSUE THREAD

**Issue by nyaroh** [JakubPluta/pyetf#2]
I converted the results to a dictionary like this 
dvwo=vwo.to_dict()
I am able to access data from various keys of the dict i.e. 
#print(dvwo.keys())
#['Dividends', 'Exposure', 'Holdings', 'Info', 'Performance', 'Ratings', 'Technicals', 'Volatility']

However print(dvwo['Volatility']) always returns {} regardless of the symbol. I noticed the HTML has this tagged as a new table i.e. <table class="table table-striped volatility-analysis-table"> - which may have broken the parsing logic.

~R

**Comment by lvxhnat** [comment]
@nyaroh  With reference to Jakub's package, I rewrote a new ETF DB python package https://github.com/lvxhnat/pyetf-scraper. Have a try at it!

**Comment by JakubPluta** [comment]
@nyaroh I fixed it
