### ISSUE TITLE
info is None

### ISSUE THREAD

**Issue by AlbinDavid** [JakubPluta/pyetf#3]
For all the etf's the info is None

```
vwo = etfdb.load_etf('VWO')
print(vwo.info) # None

```

**Comment by jiema** [comment]
I have the same issue here too.

**Comment by geofffoster** [comment]
me to.

**Comment by lvxhnat** [comment]
@jiema  @geofffoster  @AlbinDavid  With reference to Jakub's package, I rewrote a new ETF DB python package https://github.com/lvxhnat/pyetf-scraper. Have a try and let me know what you think!
