### ISSUE TITLE
etfdb.json missing !!!!????

### ISSUE THREAD

**Issue by arbitrage-technology** [JakubPluta/pyetf#4]
No such file or directory: '/Users/...../miniforge3/lib/python3.10/site-packages/pyetf/data/etfdb.json'

**Comment by lvxhnat** [comment]
@arbitrage-technology With reference to Jakub's package, I rewrote a new ETF DB python package https://github.com/lvxhnat/pyetf-scraper. Have a try and let me know what you think :)

**Comment by JakubPluta** [comment]
@arbitrage-technology I fixed issue
